In [1]:
import torch


In [2]:
torch.version.__version__

'2.9.1'

In [4]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
b = torch.ones(3,3)

In [6]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [8]:
a = a.to('mps')
b = b.to('mps')
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='mps:0')