In [18]:
a = [1.0, 2.0, 1.0]

In [19]:
a[0]

1.0

In [20]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [21]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [22]:
a[1]

tensor(1.)

In [23]:
float(a[1])

1.0

In [24]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [25]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [26]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [27]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [28]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
points.shape

torch.Size([3, 2])

In [30]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points[0, 1]

tensor(1.)

In [33]:
points[0]

tensor([4., 1.])

In [34]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='mps')
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=mps:0) of size 6]

In [35]:
points_storage = points.storage()
points_storage[0]

4.0

In [36]:
type(points.storage())

torch.storage.TypedStorage

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
# change the first element in the storage, which will also change the tensor
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [38]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])
points2 = points
points2[0] = torch.tensor([7.0, 8.0])
# changing points2 also changes points
points

tensor([[7., 8.],
        [5., 3.],
        [2., 1.]])

In [49]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[2]
second_point.storage_offset()
print(points.stride())

(2, 1)


In [50]:
second_point.size()

torch.Size([2])

In [51]:
second_point.shape

torch.Size([2])

In [52]:
points.stride()

(2, 1)

In [54]:
second_point = points[1]
print(second_point)
second_point.size()

tensor([5., 3.])


torch.Size([2])

In [55]:
second_point.storage_offset()

2

In [56]:
second_point.stride()

(1,)

In [58]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# change the first element of the 2nd row (in place)
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [59]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [64]:
points_t = points.t()
print(points_t)

points_t.stride() # after transpose, stride changes

tensor([[4., 5., 2.],
        [1., 3., 1.]])


(1, 2)

In [ ]:
# transpose operation does not create a new storage
id(points.storage()) == id(points_t.storage())

True

In [65]:
points.stride()

(2, 1)

In [66]:
points_t.stride()

(1, 2)

In [67]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [68]:
transpose_t.shape

torch.Size([5, 4, 3])

In [37]:
some_t.stride()

(20, 5, 1)

In [38]:
transpose_t.stride()

(1, 5, 20)

In [39]:
points.is_contiguous()

True

In [69]:
points_t.is_contiguous()

False

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [43]:
points_t.stride()

(1, 2)

In [ ]:
points_t_cont = points_t.contiguous() # using contiguous() to make this contiguous
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [45]:
points_t_cont.stride()

(3, 1)

In [46]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [71]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [72]:
short_points.dtype
double_points.dtype

torch.float64

In [73]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [74]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [75]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [76]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [91]:
some_list = list(range(14))
print(some_list)
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
#some_list[:-1]   # <5>
some_list[1:10:2] # <6>

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


[1, 3, 5, 7, 9]

In [ ]:
# points is a 2D tensor
print(points)
print(points[1:])       # <1>
print(points[1:, :])    # <2>
print(points[1:, 0])    # <3> becomes a 1D tensor
print(points[None])     # <4>

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [ ]:
points = torch.ones(3, 4)
points_np = points.numpy() # convert tensor to numpy array
points_np

type(points_np)

numpy.ndarray

In [ ]:
points = torch.from_numpy(points_np) # create tensor from numpy array
type(points)

torch.Tensor

In [57]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [58]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [59]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [60]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [61]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [62]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [63]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [64]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [65]:
points_gpu = points.to(device='cuda')

In [66]:
points_gpu = points.to(device='cuda:0')

In [67]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [68]:
points_gpu = points_gpu + 4

In [69]:
points_cpu = points_gpu.to(device='cpu')

In [70]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [104]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [105]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [73]:
a = torch.ones(3, 2)

In [ ]:
a.zero_() # in-place operation
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])