In [15]:
    # Exercises
    # 1 Create a tensor a from list(range(9)). Predict and then check the size, offset,
    # and stride.
    # a Create a new tensor using b = a.view(3, 3). What does view do? Check
    # that a and b share the same storage.
    # b Create a tensor c = b[1:,1:]. Predict and then check the size, offset, and
    # stride.

import torch

t = torch.tensor(list(range(9)))
a = t
# size is 9, offset is 0, stride is 1
print("Tensor a:", t)

b = t.view(3, 3) # view does not change the storage, it just changes the shape

print("b stride:", b.stride())
print("Tensor b (view of a):", b)
print("Storage of a and b are the same:", t.storage().data_ptr() == b.storage().data_ptr())

a.storage().data_ptr()== b.storage().data_ptr()

Tensor a: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
b stride: (3, 1)
Tensor b (view of a): tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Storage of a and b are the same: True


True

In [ ]:
c = b[1:,1:] # c size is 2*2, offset is 4, stride is (3,1)
c.storage_offset()

4

In [13]:
# 2 Pick a mathematical operation like cosine or square root. Can you find a corre-
#     # sponding function in the torch library?
#     # a Apply the function element-wise to a. Why does it return an error?
#     # b What operation is required to make the function work?
#     # c Is there a version of your function that operates in place?

a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [19]:
torch.cos(b)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837],
        [ 0.9602,  0.7539, -0.1455]])

In [ ]:
print(b.type()) # 
torch.sqrt(b) # this also works since newer versions of pytorch support auto cast

torch.LongTensor


tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361],
        [2.4495, 2.6458, 2.8284]])